INSERT INTO `country` VALUES (null, 'AF', 'Afghanistan');
INSERT INTO `country` VALUES (null, 'AL', 'Albania');
INSERT INTO `country` VALUES (null, 'DZ', 'Algeria');
INSERT INTO `country` VALUES (null, 'DS', 'American Samoa');
INSERT INTO `country` VALUES (null, 'AD', 'Andorra');
INSERT INTO `country` VALUES (null, 'AO', 'Angola');
INSERT INTO `country` VALUES (null, 'AI', 'Anguilla');
INSERT INTO `country` VALUES (null, 'AQ', 'Antarctica');
INSERT INTO `country` VALUES (null, 'AG', 'Antigua and Barbuda');
INSERT INTO `country` VALUES (null, 'AR', 'Argentina');
INSERT INTO `country` VALUES (null, 'AM', 'Armenia');
INSERT INTO `country` VALUES (null, 'AW', 'Aruba');
INSERT INTO `country` VALUES (null, 'AU', 'Australia');
INSERT INTO `country` VALUES (null, 'AT', 'Austria');
INSERT INTO `country` VALUES (null, 'AZ', 'Azerbaijan');
INSERT INTO `country` VALUES (null, 'BS', 'Bahamas');
INSERT INTO `country` VALUES (null, 'BH', 'Bahrain');
INSERT INTO `country` VALUES (null, 'BD', 'Bangladesh');
INSERT INTO `country` VALUES (null, 'BB', 'Barbados');
INSERT INTO `country` VALUES (null, 'BY', 'Belarus');
INSERT INTO `country` VALUES (null, 'BE', 'Belgium');
INSERT INTO `country` VALUES (null, 'BZ', 'Belize');
INSERT INTO `country` VALUES (null, 'BJ', 'Benin');
INSERT INTO `country` VALUES (null, 'BM', 'Bermuda');
INSERT INTO `country` VALUES (null, 'BT', 'Bhutan');
INSERT INTO `country` VALUES (null, 'BO', 'Bolivia');
INSERT INTO `country` VALUES (null, 'BA', 'Bosnia and Herzegovina');
INSERT INTO `country` VALUES (null, 'BW', 'Botswana');
INSERT INTO `country` VALUES (null, 'BV', 'Bouvet Island');
INSERT INTO `country` VALUES (null, 'BR', 'Brazil');
INSERT INTO `country` VALUES (null, 'IO', 'British Indian Ocean Territory');
INSERT INTO `country` VALUES (null, 'BN', 'Brunei Darussalam');
INSERT INTO `country` VALUES (null, 'BG', 'Bulgaria');
INSERT INTO `country` VALUES (null, 'BF', 'Burkina Faso');
INSERT INTO `country` VALUES (null, 'BI', 'Burundi');
INSERT INTO `country` VALUES (null, 'KH', 'Cambodia');
INSERT INTO `country` VALUES (null, 'CM', 'Cameroon');
INSERT INTO `country` VALUES (null, 'CA', 'Canada');
INSERT INTO `country` VALUES (null, 'CV', 'Cape Verde');
INSERT INTO `country` VALUES (null, 'KY', 'Cayman Islands');
INSERT INTO `country` VALUES (null, 'CF', 'Central African Republic');
INSERT INTO `country` VALUES (null, 'TD', 'Chad');
INSERT INTO `country` VALUES (null, 'CL', 'Chile');
INSERT INTO `country` VALUES (null, 'CN', 'China');
INSERT INTO `country` VALUES (null, 'CX', 'Christmas Island');
INSERT INTO `country` VALUES (null, 'CC', 'Cocos (Keeling) Islands');
INSERT INTO `country` VALUES (null, 'CO', 'Colombia');
INSERT INTO `country` VALUES (null, 'KM', 'Comoros');
INSERT INTO `country` VALUES (null, 'CG', 'Congo');
INSERT INTO `country` VALUES (null, 'CK', 'Cook Islands');
INSERT INTO `country` VALUES (null, 'CR', 'Costa Rica');
INSERT INTO `country` VALUES (null, 'HR', 'Croatia (Hrvatska)');
INSERT INTO `country` VALUES (null, 'CU', 'Cuba');
INSERT INTO `country` VALUES (null, 'CY', 'Cyprus');
INSERT INTO `country` VALUES (null, 'CZ', 'Czech Republic');
INSERT INTO `country` VALUES (null, 'DK', 'Denmark');
INSERT INTO `country` VALUES (null, 'DJ', 'Djibouti');
INSERT INTO `country` VALUES (null, 'DM', 'Dominica');
INSERT INTO `country` VALUES (null, 'DO', 'Dominican Republic');
INSERT INTO `country` VALUES (null, 'TP', 'East Timor');
INSERT INTO `country` VALUES (null, 'EC', 'Ecuador');
INSERT INTO `country` VALUES (null, 'EG', 'Egypt');
INSERT INTO `country` VALUES (null, 'SV', 'El Salvador');
INSERT INTO `country` VALUES (null, 'GQ', 'Equatorial Guinea');
INSERT INTO `country` VALUES (null, 'ER', 'Eritrea');
INSERT INTO `country` VALUES (null, 'EE', 'Estonia');
INSERT INTO `country` VALUES (null, 'ET', 'Ethiopia');
INSERT INTO `country` VALUES (null, 'FK', 'Falkland Islands (Malvinas)');
INSERT INTO `country` VALUES (null, 'FO', 'Faroe Islands');
INSERT INTO `country` VALUES (null, 'FJ', 'Fiji');
INSERT INTO `country` VALUES (null, 'FI', 'Finland');
INSERT INTO `country` VALUES (null, 'FR', 'France');
INSERT INTO `country` VALUES (null, 'FX', 'France, Metropolitan');
INSERT INTO `country` VALUES (null, 'GF', 'French Guiana');
INSERT INTO `country` VALUES (null, 'PF', 'French Polynesia');
INSERT INTO `country` VALUES (null, 'TF', 'French Southern Territories');
INSERT INTO `country` VALUES (null, 'GA', 'Gabon');
INSERT INTO `country` VALUES (null, 'GM', 'Gambia');
INSERT INTO `country` VALUES (null, 'GE', 'Georgia');
INSERT INTO `country` VALUES (null, 'DE', 'Germany');
INSERT INTO `country` VALUES (null, 'GH', 'Ghana');
INSERT INTO `country` VALUES (null, 'GI', 'Gibraltar');
INSERT INTO `country` VALUES (null, 'GK', 'Guernsey');
INSERT INTO `country` VALUES (null, 'GR', 'Greece');
INSERT INTO `country` VALUES (null, 'GL', 'Greenland');
INSERT INTO `country` VALUES (null, 'GD', 'Grenada');
INSERT INTO `country` VALUES (null, 'GP', 'Guadeloupe');
INSERT INTO `country` VALUES (null, 'GU', 'Guam');
INSERT INTO `country` VALUES (null, 'GT', 'Guatemala');
INSERT INTO `country` VALUES (null, 'GN', 'Guinea');
INSERT INTO `country` VALUES (null, 'GW', 'Guinea-Bissau');
INSERT INTO `country` VALUES (null, 'GY', 'Guyana');
INSERT INTO `country` VALUES (null, 'HT', 'Haiti');
INSERT INTO `country` VALUES (null, 'HM', 'Heard and Mc Donald Islands');
INSERT INTO `country` VALUES (null, 'HN', 'Honduras');
INSERT INTO `country` VALUES (null, 'HK', 'Hong Kong');
INSERT INTO `country` VALUES (null, 'HU', 'Hungary');
INSERT INTO `country` VALUES (null, 'IS', 'Iceland');
INSERT INTO `country` VALUES (null, 'IN', 'India');
INSERT INTO `country` VALUES (null, 'IM', 'Isle of Man');
INSERT INTO `country` VALUES (null, 'ID', 'Indonesia');
INSERT INTO `country` VALUES (null, 'IR', 'Iran (Islamic Republic of)');
INSERT INTO `country` VALUES (null, 'IQ', 'Iraq');
INSERT INTO `country` VALUES (null, 'IE', 'Ireland');
INSERT INTO `country` VALUES (null, 'IL', 'Israel');
INSERT INTO `country` VALUES (null, 'IT', 'Italy');
INSERT INTO `country` VALUES (null, 'CI', 'Ivory Coast');
INSERT INTO `country` VALUES (null, 'JE', 'Jersey');
INSERT INTO `country` VALUES (null, 'JM', 'Jamaica');
INSERT INTO `country` VALUES (null, 'JP', 'Japan');
INSERT INTO `country` VALUES (null, 'JO', 'Jordan');
INSERT INTO `country` VALUES (null, 'KZ', 'Kazakhstan');
INSERT INTO `country` VALUES (null, 'KE', 'Kenya');
INSERT INTO `country` VALUES (null, 'KI', 'Kiribati');
INSERT INTO `country` VALUES (null, 'KP', 'Korea, Democratic People''s Republic of');
INSERT INTO `country` VALUES (null, 'KR', 'Korea, Republic of');
INSERT INTO `country` VALUES (null, 'XK', 'Kosovo');
INSERT INTO `country` VALUES (null, 'KW', 'Kuwait');
INSERT INTO `country` VALUES (null, 'KG', 'Kyrgyzstan');
INSERT INTO `country` VALUES (null, 'LA', 'Lao People''s Democratic Republic');
INSERT INTO `country` VALUES (null, 'LV', 'Latvia');
INSERT INTO `country` VALUES (null, 'LB', 'Lebanon');
INSERT INTO `country` VALUES (null, 'LS', 'Lesotho');
INSERT INTO `country` VALUES (null, 'LR', 'Liberia');
INSERT INTO `country` VALUES (null, 'LY', 'Libyan Arab Jamahiriya');
INSERT INTO `country` VALUES (null, 'LI', 'Liechtenstein');
INSERT INTO `country` VALUES (null, 'LT', 'Lithuania');
INSERT INTO `country` VALUES (null, 'LU', 'Luxembourg');
INSERT INTO `country` VALUES (null, 'MO', 'Macau');
INSERT INTO `country` VALUES (null, 'MK', 'Macedonia');
INSERT INTO `country` VALUES (null, 'MG', 'Madagascar');
INSERT INTO `country` VALUES (null, 'MW', 'Malawi');
INSERT INTO `country` VALUES (null, 'MY', 'Malaysia');
INSERT INTO `country` VALUES (null, 'MV', 'Maldives');
INSERT INTO `country` VALUES (null, 'ML', 'Mali');
INSERT INTO `country` VALUES (null, 'MT', 'Malta');
INSERT INTO `country` VALUES (null, 'MH', 'Marshall Islands');
INSERT INTO `country` VALUES (null, 'MQ', 'Martinique');
INSERT INTO `country` VALUES (null, 'MR', 'Mauritania');
INSERT INTO `country` VALUES (null, 'MU', 'Mauritius');
INSERT INTO `country` VALUES (null, 'TY', 'Mayotte');
INSERT INTO `country` VALUES (null, 'MX', 'Mexico');
INSERT INTO `country` VALUES (null, 'FM', 'Micronesia, Federated States of');
INSERT INTO `country` VALUES (null, 'MD', 'Moldova, Republic of');
INSERT INTO `country` VALUES (null, 'MC', 'Monaco');
INSERT INTO `country` VALUES (null, 'MN', 'Mongolia');
INSERT INTO `country` VALUES (null, 'ME', 'Montenegro');
INSERT INTO `country` VALUES (null, 'MS', 'Montserrat');
INSERT INTO `country` VALUES (null, 'MA', 'Morocco');
INSERT INTO `country` VALUES (null, 'MZ', 'Mozambique');
INSERT INTO `country` VALUES (null, 'MM', 'Myanmar');
INSERT INTO `country` VALUES (null, 'NA', 'Namibia');
INSERT INTO `country` VALUES (null, 'NR', 'Nauru');
INSERT INTO `country` VALUES (null, 'NP', 'Nepal');
INSERT INTO `country` VALUES (null, 'NL', 'Netherlands');
INSERT INTO `country` VALUES (null, 'AN', 'Netherlands Antilles');
INSERT INTO `country` VALUES (null, 'NC', 'New Caledonia');
INSERT INTO `country` VALUES (null, 'NZ', 'New Zealand');
INSERT INTO `country` VALUES (null, 'NI', 'Nicaragua');
INSERT INTO `country` VALUES (null, 'NE', 'Niger');
INSERT INTO `country` VALUES (null, 'NG', 'Nigeria');
INSERT INTO `country` VALUES (null, 'NU', 'Niue');
INSERT INTO `country` VALUES (null, 'NF', 'Norfolk Island');
INSERT INTO `country` VALUES (null, 'MP', 'Northern Mariana Islands');
INSERT INTO `country` VALUES (null, 'NO', 'Norway');
INSERT INTO `country` VALUES (null, 'OM', 'Oman');
INSERT INTO `country` VALUES (null, 'PK', 'Pakistan');
INSERT INTO `country` VALUES (null, 'PW', 'Palau');
INSERT INTO `country` VALUES (null, 'PS', 'Palestine');
INSERT INTO `country` VALUES (null, 'PA', 'Panama');
INSERT INTO `country` VALUES (null, 'PG', 'Papua New Guinea');
INSERT INTO `country` VALUES (null, 'PY', 'Paraguay');
INSERT INTO `country` VALUES (null, 'PE', 'Peru');
INSERT INTO `country` VALUES (null, 'PH', 'Philippines');
INSERT INTO `country` VALUES (null, 'PN', 'Pitcairn');
INSERT INTO `country` VALUES (null, 'PL', 'Poland');
INSERT INTO `country` VALUES (null, 'PT', 'Portugal');
INSERT INTO `country` VALUES (null, 'PR', 'Puerto Rico');
INSERT INTO `country` VALUES (null, 'QA', 'Qatar');
INSERT INTO `country` VALUES (null, 'RE', 'Reunion');
INSERT INTO `country` VALUES (null, 'RO', 'Romania');
INSERT INTO `country` VALUES (null, 'RU', 'Russian Federation');
INSERT INTO `country` VALUES (null, 'RW', 'Rwanda');
INSERT INTO `country` VALUES (null, 'KN', 'Saint Kitts and Nevis');
INSERT INTO `country` VALUES (null, 'LC', 'Saint Lucia');
INSERT INTO `country` VALUES (null, 'VC', 'Saint Vincent and the Grenadines');
INSERT INTO `country` VALUES (null, 'WS', 'Samoa');
INSERT INTO `country` VALUES (null, 'SM', 'San Marino');
INSERT INTO `country` VALUES (null, 'ST', 'Sao Tome and Principe');
INSERT INTO `country` VALUES (null, 'SA', 'Saudi Arabia');
INSERT INTO `country` VALUES (null, 'SN', 'Senegal');
INSERT INTO `country` VALUES (null, 'RS', 'Serbia');
INSERT INTO `country` VALUES (null, 'SC', 'Seychelles');
INSERT INTO `country` VALUES (null, 'SL', 'Sierra Leone');
INSERT INTO `country` VALUES (null, 'SG', 'Singapore');
INSERT INTO `country` VALUES (null, 'SK', 'Slovakia');
INSERT INTO `country` VALUES (null, 'SI', 'Slovenia');
INSERT INTO `country` VALUES (null, 'SB', 'Solomon Islands');
INSERT INTO `country` VALUES (null, 'SO', 'Somalia');
INSERT INTO `country` VALUES (null, 'ZA', 'South Africa');
INSERT INTO `country` VALUES (null, 'GS', 'South Georgia South Sandwich Islands');
INSERT INTO `country` VALUES (null, 'SS', 'South Sudan');
INSERT INTO `country` VALUES (null, 'ES', 'Spain');
INSERT INTO `country` VALUES (null, 'LK', 'Sri Lanka');
INSERT INTO `country` VALUES (null, 'SH', 'St. Helena');
INSERT INTO `country` VALUES (null, 'PM', 'St. Pierre and Miquelon');
INSERT INTO `country` VALUES (null, 'SD', 'Sudan');
INSERT INTO `country` VALUES (null, 'SR', 'Suriname');
INSERT INTO `country` VALUES (null, 'SJ', 'Svalbard and Jan Mayen Islands');
INSERT INTO `country` VALUES (null, 'SZ', 'Swaziland');
INSERT INTO `country` VALUES (null, 'SE', 'Sweden');
INSERT INTO `country` VALUES (null, 'CH', 'Switzerland');
INSERT INTO `country` VALUES (null, 'SY', 'Syrian Arab Republic');
INSERT INTO `country` VALUES (null, 'TW', 'Taiwan');
INSERT INTO `country` VALUES (null, 'TJ', 'Tajikistan');
INSERT INTO `country` VALUES (null, 'TZ', 'Tanzania, United Republic of');
INSERT INTO `country` VALUES (null, 'TH', 'Thailand');
INSERT INTO `country` VALUES (null, 'TG', 'Togo');
INSERT INTO `country` VALUES (null, 'TK', 'Tokelau');
INSERT INTO `country` VALUES (null, 'TO', 'Tonga');
INSERT INTO `country` VALUES (null, 'TT', 'Trinidad and Tobago');
INSERT INTO `country` VALUES (null, 'TN', 'Tunisia');
INSERT INTO `country` VALUES (null, 'TR', 'Turkey');
INSERT INTO `country` VALUES (null, 'TM', 'Turkmenistan');
INSERT INTO `country` VALUES (null, 'TC', 'Turks and Caicos Islands');
INSERT INTO `country` VALUES (null, 'TV', 'Tuvalu');
INSERT INTO `country` VALUES (null, 'UG', 'Uganda');
INSERT INTO `country` VALUES (null, 'UA', 'Ukraine');
INSERT INTO `country` VALUES (null, 'AE', 'United Arab Emirates');
INSERT INTO `country` VALUES (null, 'GB', 'United Kingdom');
INSERT INTO `country` VALUES (null, 'US', 'United States');
INSERT INTO `country` VALUES (null, 'UM', 'United States minor outlying islands');
INSERT INTO `country` VALUES (null, 'UY', 'Uruguay');
INSERT INTO `country` VALUES (null, 'UZ', 'Uzbekistan');
INSERT INTO `country` VALUES (null, 'VU', 'Vanuatu');
INSERT INTO `country` VALUES (null, 'VA', 'Vatican City State');
INSERT INTO `country` VALUES (null, 'VE', 'Venezuela');
INSERT INTO `country` VALUES (null, 'VN', 'Vietnam');
INSERT INTO `country` VALUES (null, 'VG', 'Virgin Islands (British)');
INSERT INTO `country` VALUES (null, 'VI', 'Virgin Islands (U.S.)');
INSERT INTO `country` VALUES (null, 'WF', 'Wallis and Futuna Islands');
INSERT INTO `country` VALUES (null, 'EH', 'Western Sahara');
INSERT INTO `country` VALUES (null, 'YE', 'Yemen');
INSERT INTO `country` VALUES (null, 'ZR', 'Zaire');
INSERT INTO `country` VALUES (null, 'ZM', 'Zambia');
INSERT INTO `country` VALUES (null, 'ZW', 'Zimbabwe');

INSERT INTO `country` VALUES (1616, 'TC', 'TestCountry');

INSERT INTO `city` VALUES (null, 'Berlin', (SELECT id FROM `country` WHERE name_country = 'Germany'));
INSERT INTO `city` VALUES (null, 'Helsinki', (SELECT id FROM `country` WHERE name_country = 'Finland'));
INSERT INTO `city` VALUES (null, 'Budapest', (SELECT id FROM `country` WHERE name_country = 'Hungary'));
INSERT INTO `city` VALUES (null, 'Prague', (SELECT id FROM `country` WHERE name_country = 'Czech Republic'));
INSERT INTO `city` VALUES (null, 'Amsterdam', (SELECT id FROM `country` WHERE name_country = 'Netherlands'));
INSERT INTO `city` VALUES (null, 'London', (SELECT id FROM `country` WHERE name_country = 'United Kingdom'));
INSERT INTO `city` VALUES (null, 'Brighton', (SELECT id FROM `country` WHERE name_country = 'United Kingdom'));
INSERT INTO `city` VALUES (null, 'Bucharest', (SELECT id FROM `country` WHERE name_country = 'Romania'));
INSERT INTO `city` VALUES (null, 'Paris', (SELECT id FROM `country` WHERE name_country = 'France'));
INSERT INTO `city` VALUES (null, 'Geneva', (SELECT id FROM `country` WHERE name_country = 'Switzerland'));
INSERT INTO `city` VALUES (null, 'Lausanne', (SELECT id FROM `country` WHERE name_country = 'Switzerland'));
INSERT INTO `city` VALUES (null, 'Brussels', (SELECT id FROM `country` WHERE name_country = 'Belgium'));
INSERT INTO `city` VALUES (null, 'Stockholm', (SELECT id FROM `country` WHERE name_country = 'Sweden'));
INSERT INTO `city` VALUES (null, 'Vienna', (SELECT id FROM `country` WHERE name_country = 'Austria'));
INSERT INTO `city` VALUES (null, 'Madrid', (SELECT id FROM `country` WHERE name_country = 'Spain'));
INSERT INTO `city` VALUES (null, 'Barcelona', (SELECT id FROM `country` WHERE name_country = 'Spain'));
INSERT INTO `city` VALUES (null, 'Valencia', (SELECT id FROM `country` WHERE name_country = 'Spain'));
INSERT INTO `city` VALUES (null, 'Porto', (SELECT id FROM `country` WHERE name_country = 'Portugal'));
INSERT INTO `city` VALUES (null, 'Lisbon', (SELECT id FROM `country` WHERE name_country = 'Portugal'));
INSERT INTO `city` VALUES (null, 'Oslo', (SELECT id FROM `country` WHERE name_country = 'Norway'));
INSERT INTO `city` VALUES (null, 'Dublin', (SELECT id FROM `country` WHERE name_country = 'Ireland'));

INSERT INTO `city` VALUES (1616, 'TestCity', (SELECT id FROM `country` WHERE name_country = 'TestCountry'));

INSERT INTO `category` VALUES (NULL, 'Bar/Pub');
INSERT INTO `category` VALUES (NULL, 'Club');
INSERT INTO `category` VALUES (NULL, 'Restaurant');
INSERT INTO `category` VALUES (NULL, 'Coffee');
INSERT INTO `category` VALUES (NULL, 'Brunch');
INSERT INTO `category` VALUES (NULL, 'Visit');
INSERT INTO `category` VALUES (NULL, 'Urbex');
INSERT INTO `category` VALUES (NULL, 'Rooftop');
INSERT INTO `category` VALUES (NULL, 'Chill out places');

INSERT INTO `category` VALUES (1616, 'test cat');

INSERT INTO `place` VALUES (NULL, 'Kazinczy u. 14', 'Huge pub with old mismatched items & a disused Trabant car, with music, food, market & a garden.', 'Szimpla Kert', (SELECT id FROM `city` WHERE name_city = 'Budapest'));
INSERT INTO `place_category` VALUES (NULL, (SELECT id FROM `category` WHERE category_name = 'Bar/Pub'), (SELECT id FROM `place` WHERE name_place = 'Szimpla Kert'));
INSERT INTO `place_category` VALUES (NULL, (SELECT id FROM `category` WHERE category_name = 'Club'), (SELECT id FROM `place` WHERE name_place = 'Szimpla Kert'));
INSERT INTO `place` VALUES (NULL, 'Akácfa utca 49-51', 'Huge complex converted from 2 houses, with theatrical decor, 6 bars, 3 dance floors & 2 gardens.', 'Instant', (SELECT id FROM `city` WHERE name_city = 'Budapest'));
INSERT INTO `place_category` VALUES (NULL, (SELECT id FROM `category` WHERE category_name = 'Bar/Pub'), (SELECT id FROM `place` WHERE name_place = 'Instant'));
INSERT INTO `place_category` VALUES (NULL, (SELECT id FROM `category` WHERE category_name = 'Club'), (SELECT id FROM `place` WHERE name_place = 'Instant'));
INSERT INTO `place` VALUES (NULL, 'Lovas út 4/c', 'The Hospital in the Rock Nuclear Bunker Museum (Sziklakórház Atombunker Múzeum) is part of an approximately 6-mile (10-km) stretch of interconnected caves and cellars beneath Buda Castle Hill. This museum is dedicated to a former secret emergency hospital and nuclear bunker.', 'Hospital in the Rock', (SELECT id FROM `city` WHERE name_city = 'Budapest'));
INSERT INTO `place_category` VALUES (NULL, (SELECT id FROM `category` WHERE category_name = 'Visit'), (SELECT id FROM `place` WHERE name_place = 'Hospital in the Rock'));
INSERT INTO `place` VALUES (NULL, 'Kelenhegyi út 4', 'Gellért Thermal Baths is the art nouveau, historical thermal bath of Budapest since 1918. It offers both health and wellness services, such as aroma and thermal massages, lavender treatment, spa pedicure and private bathing. Relaxing wellness services at Gellért Baths, a must-to-do programme in Budapest.', 'Gellert bath', (SELECT id FROM `city` WHERE name_city = 'Budapest'));
INSERT INTO `place_category` VALUES (NULL, (SELECT id FROM `category` WHERE category_name = 'Chill out places'), (SELECT id FROM `place` WHERE name_place = 'Gellert bath'));
INSERT INTO `place` VALUES (NULL, 'Akácfa u. 49-51', 'If you’re tired of average party places spend a night at Fogas Ház, one of the vanguards of the ruin pub scene in Akácfa utca. This pub has long been a catchment basin for arts and artists, but it was not until 2017 that it reached its current form and popularity.', 'Fogas Ház', (SELECT id FROM `city` WHERE name_city = 'Budapest'));
INSERT INTO `place_category` VALUES (NULL, (SELECT id FROM `category` WHERE category_name = 'Bar/Pub'), (SELECT id FROM `place` WHERE name_place = 'Fogas Ház'));

INSERT INTO `place` VALUES (NULL, 'Karl-Marx-Straße 66 (Located in Neukölln Arcaden rooftop)', 'Rooftop Bar Klunkerkranich is hardly a secret anymore, this place is still super cool and unique. Take the subway to Rathaus Neukölln  (U7) and walk to the somewhat sad looking Neukölln Arkaden (mall). Once in there, find the elevators that take you to the highest possible floor. Once you get out, you will find yourself in a parking garage atop the mall. Walk up to the ramp with the walls adorned by a funky vertical garden. You are now at one of the funkiest and coolest places to watch the sunset in Berlin. Wether you sit by the rooftop garden or on the benches, tables and steps of the bar area, you are in for a treat.', 'Klunkerkranich', (SELECT id FROM `city` WHERE name_city = 'Berlin'));
INSERT INTO `place_category` VALUES (NULL, (SELECT id FROM `category` WHERE category_name = 'Bar/Pub'), (SELECT id FROM `place` WHERE name_place = 'Klunkerkranich'));
INSERT INTO `place_category` VALUES (NULL, (SELECT id FROM `category` WHERE category_name = 'Rooftop'), (SELECT id FROM `place` WHERE name_place = 'Klunkerkranich'));
INSERT INTO `place` VALUES (NULL, 'Budapester Str. 40 (rooftop)', 'The top floor Monkey Bar with panoramic view and perfect sundowner terrace is the hot spot after dusk. An international choice of drinks and fine wine as well as bar snacks from the NENI kitchen are served. Regular DJ lines and live music events take place at the Monkey Bar. The bar can be booked exclusively upon request and has a direct express lift from street level.', 'Monkey Bar', (SELECT id FROM `city` WHERE name_city = 'Berlin'));
INSERT INTO `place_category` VALUES (NULL, (SELECT id FROM `category` WHERE category_name = 'Bar/Pub'), (SELECT id FROM `place` WHERE name_place = 'Monkey Bar'));
INSERT INTO `place_category` VALUES (NULL, (SELECT id FROM `category` WHERE category_name = 'Rooftop'), (SELECT id FROM `place` WHERE name_place = 'Monkey Bar'));
INSERT INTO `place` VALUES (NULL, 'Sonnenallee 221', 'Housed in a former grain mill in Neukölln, Griessmuehle has one large dance floor inside, a smaller space in the basement and a half-outdoor spot where the club hosts afterhours. It has a sprawling garden complete with grain silos, various makeshift structures and benches looking out onto a canal. Programming touches on all of Berlin\'s favorite sounds—house, techno, disco, even a bit of UK bass.', 'Griessmuehle', (SELECT id FROM `city` WHERE name_city = 'Berlin'));
INSERT INTO `place_category` VALUES (NULL, (SELECT id FROM `category` WHERE category_name = 'Club'), (SELECT id FROM `place` WHERE name_place = 'Griessmuehle'));

INSERT INTO `place` VALUES (1616, 'gerrgnvwjbbg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'LoremForever', 1616);
INSERT INTO `place_category` VALUES (1616, 1616, 1616);
