const ActionTypes = {
// User component to be changed by jose whereever needed

  // * Login
  LOGIN_REQ:          'LOGIN_REQ',
  LOGIN_OK:           'LOGIN_OK',
  LOGIN_X:            'LOGIN_X',
  LOGOUT:             'LOGOUT',

  EMAIL_CHANGED:      'EMAIL_CHANGED',
  PASSWORD_CHANGED:   'PASSWORD_CHANGED',


  // Client
  CLIENTS_ALL_REQ:  'CLIENTS_ALL_REQ',
  CLIENTS_ALL_OK:   'CLIENTS_ALL_OK',
  CLIENTS_ALL_X:    'CLIENTS_ALL_X',

  CLIENT_DELETE_REQ:  'CLIENT_DELETE_REQ',
  CLIENT_DELETE_OK:   'CLIENT_DELETE_OK',
  CLIENT_DELETE_X:    'CLIENT_DELETE_X',

  CLIENT_ADD_REQ:   'CLIENT_ADD_REQ',
  CLIENT_ADD_OK:    'CLIENT_ADD_OK',
  CLIENT_ADD_X:     'CLIENT_ADD_X',

  CLIENT_FETCHBYID_REQ:   'CLIENT_FETCHBYID_REQ',
  CLIENT_FETCHBYID_OK:    'CLIENT_FETCHBYID_OK',
  CLIENT_FETCHBYID_X:     'CLIENT_FETCHBYID_X',

  CLIENT_CURRENT_RESET: 'CLIENT_CURRENT_RESET',


  //People
  PEOPLE_ALL_REQ: 'PEOPLE_ALL_REQ',
  PEOPLE_ALL_OK: 'PEOPLE_ALL_OK',
  PEOPLE_ALL_X: 'PEOPLE_ALL_X',

  // Location
  LOCATIONS_ALL_REQ:  'LOCATIONS_ALL_REQ',
  LOCATIONS_ALL_OK:   'LOCATIONS_ALL_OK',
  LOCATIONS_ALL_X:    'LOCATIONS_ALL_X',

  LOCATION_DELETE_REQ:  'LOCATION_DELETE_REQ',
  LOCATION_DELETE_OK:   'LOCATION_DELETE_OK',
  LOCATION_DELETE_X:    'LOCATION_DELETE_X',

  LOCATION_ADD_REQ:   'LOCATION_ADD_REQ',
  LOCATION_ADD_OK:    'LOCATION_ADD_OK',
  LOCATION_ADD_X:     'LOCATION_ADD_X',

  LOCATION_FETCHBYID_REQ:   'LOCATION_FETCHBYID_REQ',
  LOCATION_FETCHBYID_OK:    'LOCATION_FETCHBYID_OK',
  LOCATION_FETCHBYID_X:     'LOCATION_FETCHBYID_X',

  LOCATION_CURRENT_RESET:   'LOCATION_CURRENT_RESET',


  // Project
  PROJECTS_ALL_REQ:   'PROJECTS_ALL_REQ',
  PROJECTS_ALL_OK:    'PROJECTS_ALL_OK',
  PROJECTS_ALL_X:     'PROJECTS_ALL_X',


  //Skill
  SKILL_ALL_REQ: 'SKILL_ALL_REQ',
  SKILL_ALL_OK: 'SKILL_ALL_OK',
  SKILL_ALL_X: 'SKILL_ALL_X',

  SKILL_DELETE_REQ: 'SKILL_DELETE_REQ',
  SKILL_DELETE_OK: 'SKILL_DELETE_OK',
  SKILL_DELETE_X: 'SKILL_DELETE_X',

  SKILL_FETCHBYID_REQ: 'SKILL_FETCHBYID_REQ',
  SKILL_FETCHBYID_OK: 'SKILL_FETCHBYID_OK',
  SKILL_FETCHBYID_X: 'SKILL_FETCHBYID_X',

  SKILL_CURRENT_RESET: 'SKILL_CURRENT_RESET',

  SKILL_ADD_REQ: 'SKILL_ADD_REQ',
  SKILL_ADD_OK: 'SKILL_ADD_OK',
  SKILL_ADD_X: 'SKILL_ADD_X',


  //Skill Category
  SKILL_CATEGORY_ALL_REQ: 'SKILL_CATEGORY_ALL_REQ',
  SKILL_CATEGORY_ALL_OK: 'SKILL_CATEGORY_ALL_OK',
  SKILL_CATEGORY_ALL_X: 'SKILL_CATEGORY_ALL_X',

  SKILL_CATEGORY_DELETE_REQ: 'SKILL_CATEGORY_DELETE_REQ',
  SKILL_CATEGORY_DELETE_OK: 'SKILL_CATEGORY_DELETE_OK',
  SKILL_CATEGORY_DELETE_X: 'SKILL_CATEGORY_DELETE_X',

  SKILL_CATEGORY_ADD_REQ: 'SKILL_CATEGORY_ADD_REQ',
  SKILL_CATEGORY_ADD_OK: 'SKILL_CATEGORY_ADD_OK',
  SKILL_CATEGORY_ADD_X: 'SKILL_CATEGORY_ADD_X',

};

export default ActionTypes;

